import type { BookingsResponse, PlayerStats, UpcomingGame, FeedItem } from "./types";

// Mutable so join mock can update in-memory state
export const MOCK_BOOKINGS: BookingsResponse = {
    bookings: [
        {
            bookingId: "00000000-0000-0000-0000-000000000001",
            clubId: "club-001",
            clubName: "Kora West Island",
            courtName: "Court 1",
            type: "Game",
            startsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
            endsAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
            timeZoneId: "UTC",
            isPrivate: false,
            participantsCount: 2,
            capacity: 4,
            spotsOpen: 2,
            amIIn: false,
        },
        {
            bookingId: "00000000-0000-0000-0000-000000000002",
            clubId: "club-001",
            clubName: "Kora West Island",
            courtName: "Court 2",
            type: "Game",
            startsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
            endsAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
            timeZoneId: "UTC",
            isPrivate: false,
            participantsCount: 3,
            capacity: 4,
            spotsOpen: 1,
            amIIn: true,
        },
        {
            bookingId: "00000000-0000-0000-0000-000000000003",
            clubId: "club-002",
            clubName: "Kora Cathcart",
            courtName: "Court A",
            type: "DayUse",
            startsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
            endsAt: new Date(Date.now() + 32 * 60 * 60 * 1000).toISOString(),
            timeZoneId: "UTC",
            isPrivate: false,
            participantsCount: 8,
            capacity: 16,
            spotsOpen: 8,
            amIIn: false,
        },
        {
            bookingId: "00000000-0000-0000-0000-000000000004",
            clubId: "club-002",
            clubName: "Kora Cathcart",
            courtName: "Court B",
            type: "Game",
            startsAt: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
            endsAt: new Date(Date.now() + 27 * 60 * 60 * 1000).toISOString(),
            timeZoneId: "UTC",
            isPrivate: false,
            participantsCount: 4,
            capacity: 4,
            spotsOpen: 0,
            amIIn: false,
        },
        {
            bookingId: "00000000-0000-0000-0000-000000000005",
            clubId: "club-003",
            clubName: "Kora Pitt Meadows",
            courtName: "Court 3",
            type: "Game",
            startsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
            endsAt: new Date(Date.now() + 49 * 60 * 60 * 1000).toISOString(),
            timeZoneId: "UTC",
            isPrivate: false,
            participantsCount: 0,
            capacity: 4,
            spotsOpen: 4,
            amIIn: false,
        },
        {
            bookingId: "00000000-0000-0000-0000-000000000006",
            clubId: "club-001",
            clubName: "Kora West Island",
            courtName: "Court 3",
            type: "DayUse",
            startsAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
            endsAt: new Date(Date.now() + 80 * 60 * 60 * 1000).toISOString(),
            timeZoneId: "UTC",
            isPrivate: false,
            participantsCount: 12,
            capacity: 20,
            spotsOpen: 8,
            amIIn: false,
        },
    ],
};

export const MOCK_PLAYER_STATS: PlayerStats = {
    gamesPlayed: 42,
    gamesWon: 28,
    gamesLost: 14,
    rating: 4.3,
    rank: "Gold",
    rankPoints: 1240,
    rankPointsToNext: 2000,
    medals: [
        { id: "1", name: "First Win", description: "Ganhou o primeiro jogo", earnedAt: "2026-01-10T00:00:00Z" },
        { id: "2", name: "10 Games Played", description: "Participou de 10 jogos", earnedAt: "2026-02-15T00:00:00Z" },
        { id: "3", name: "Hat-trick", description: "3 vitórias seguidas", earnedAt: "2026-03-01T00:00:00Z" },
        { id: "4", name: "Club Regular", description: "Jogou em 3 clubes diferentes", earnedAt: "2026-04-05T00:00:00Z" },
    ],
};

export const MOCK_UPCOMING_GAMES: UpcomingGame[] = [
    {
        bookingId: "00000000-0000-0000-0000-000000000002",
        clubName: "Kora West Island",
        courtName: "Court 2",
        type: "Game",
        startsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
        endsAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
        participantsCount: 3,
        capacity: 4,
    },
    {
        bookingId: "00000000-0000-0000-0000-000000000005",
        clubName: "Kora Pitt Meadows",
        courtName: "Court 3",
        type: "Game",
        startsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
        endsAt: new Date(Date.now() + 49 * 60 * 60 * 1000).toISOString(),
        participantsCount: 0,
        capacity: 4,
    },
];

export const MOCK_FEED_ITEMS: FeedItem[] = [
    {
        id: "f1",
        type: "championship",
        title: "Open de Verão 2026",
        body: "Inscrições abertas para o maior torneio da temporada. Mais de 60 duplas confirmadas. Venha fazer parte desta edição histórica!",
        imageUrl: "https://picsum.photos/seed/champ1/600/300",
        clubName: "Kora Arena",
        publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["torneio", "verão"],
    },
    {
        id: "f2",
        type: "event",
        title: "Noite de Padel — 20/05",
        body: "Uma noite especial com música ao vivo, sorteios e partidas temáticas para todos os níveis. Entrada gratuita para membros.",
        imageUrl: "https://picsum.photos/seed/event2/600/300",
        clubName: "Club Kora",
        publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["evento"],
    },
    {
        id: "f3",
        type: "post",
        title: "Dica da Semana: Bandeja Perfeita",
        body: "A bandeja é um dos golpes mais icônicos do padel. O segredo está na preparação antecipada e no posicionamento do corpo. Confira os erros mais comuns e como corrigi-los para dominar esse golpe de uma vez por todas.",
        clubName: "Kora West Island",
        publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["dica", "técnica"],
    },
    {
        id: "f4",
        type: "result",
        title: "Semifinal — Kora Cup 2026",
        body: "Dupla Silva/Mendes venceu Dupla Costa/Rocha por 6-3, 6-4. Grande final marcada para 24/05 às 18h.",
        clubName: "Kora Arena",
        publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["resultado", "torneio"],
    },
    {
        id: "f5",
        type: "photo",
        title: "Reformas na Quadra Central",
        body: "A quadra central do Kora West Island foi totalmente reformada. Venha conferir!",
        imageUrl: "https://picsum.photos/seed/court5/600/400",
        clubName: "Kora West Island",
        publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["clube"],
    },
    {
        id: "f6",
        type: "post",
        title: "Como Escolher a Raquete Certa para o Seu Nível",
        body: "Iniciante, intermediário ou avançado? Cada perfil exige características diferentes — peso, forma e material influenciam diretamente na sua performance. Neste post explicamos os principais pontos para não errar na hora da compra.",
        clubName: "Kora West Island",
        publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["equipamento", "dica"],
    },
    {
        id: "f7",
        type: "event",
        title: "Clínica com Profissional — 25/05",
        body: "Treinamento intensivo de 3 horas com o professor Rafael Souza, ex-top 50 nacional. Vagas limitadas a 12 participantes por turma. Inscrições até 22/05.",
        imageUrl: "https://picsum.photos/seed/clinic7/600/300",
        clubName: "Kora Cathcart",
        publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["clinica", "treino"],
    },
    {
        id: "f8",
        type: "result",
        title: "Torneio Feminino — Rodada das 8",
        body: "Dupla Ferreira/Lima eliminou Dupla Nunes/Santos por 7-5, 6-3. Semifinais acontecem no próximo sábado às 14h. Muito nível nas quadras!",
        clubName: "Kora Arena",
        publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["resultado", "feminino"],
    },
    {
        id: "f9",
        type: "post",
        title: "Posicionamento no Padel Dupla: Erros que Custam Pontos",
        body: "Ficar parado ao fundo enquanto seu parceiro sobe é um dos maiores erros do padel amador. Entenda a dinâmica do jogo paralelo e como cobrir os espaços certos para virar partidas difíceis.",
        clubName: "Club Kora",
        publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["tática", "dica"],
    },
    {
        id: "f10",
        type: "photo",
        title: "Galeria — Open de Verão 2026",
        body: "Confira os melhores momentos do primeiro dia de torneio. Grandes jogadas, emoção nas quadras e muita energia dos participantes.",
        imageUrl: "https://picsum.photos/seed/gallery10/600/400",
        clubName: "Kora Arena",
        publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["torneio", "fotos"],
    },
    {
        id: "f11",
        type: "championship",
        title: "Kora Cup Infantil — Inscrições Abertas",
        body: "Categoria juvenil para atletas de 10 a 17 anos. O torneio acontece nos dias 07 e 08 de junho no Kora Pitt Meadows. Incentive os pequenos a entrar em quadra!",
        imageUrl: "https://picsum.photos/seed/kids11/600/300",
        clubName: "Kora Pitt Meadows",
        publishedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["juvenil", "torneio"],
    },
    {
        id: "f12",
        type: "post",
        title: "Aquecimento: O Que Fazer Antes de Entrar em Quadra",
        body: "Pular o aquecimento é a receita para uma lesão. Confira a rotina de 10 minutos que os nossos professores recomendam — mobilidade de ombro, tornozelo e quadril + ativação de core.",
        clubName: "Kora West Island",
        publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        tags: ["saúde", "dica"],
    },
];
